version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "k-kazuya0926"
    allow:
      - dependency-type: "all"
