name: static-analysis
on:
  pull_request:
    paths: [".github/workflows/*.yml", ".github/workflows/*.yaml"]
  push:
    branches: [main]
    paths: [".github/workflows/*.yml", ".github/workflows/*.yaml"]
defaults: # パイプエラーを拾えるようにデフォルトシェルを設定
  run:
    shell: bash
concurrency: # コミット追加時に古いワークフローの実行を自動キャンセル
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - run: | # 静的解析の実行
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
